[project]
name = "OpenStudioLandscapes-Deadline-10-2-Worker"
description = "Deadline 10.2 Worker Feature for OpenStudioLandscapes (dep: OpenStudioLandscapes-Deadline-10-2)"
dependencies = [
    "OpenStudioLandscapes-Deadline-10-2 @ git+https://github.com/michimussato/OpenStudioLandscapes-Deadline-10-2@v1.8.0-rc1",
]

[project.urls]
Homepage = "https://github.com/michimussato/OpenStudioLandscapes-Deadline-10-2-Worker"

[project.optional-dependencies]
sbom = [
    "OpenStudioLandscapes-Deadline-10-2-Worker[graphviz]",
]
nox = [
    "OpenStudioLandscapes-Deadline-10-2-Worker[testing]",
]
readme = [
    "OpenStudioLandscapesUtil-ReadmeGenerator @ git+https://github.com/michimussato/OpenStudioLandscapesUtil-ReadmeGenerator.git@v1.8.0-rc1"
]
dev = [
    "OpenStudioLandscapes-Deadline-10-2-Worker[testing]",
    "OpenStudioLandscapes-Deadline-10-2-Worker[lint]",
    "OpenStudioLandscapes-Deadline-10-2-Worker[nox]",
    "OpenStudioLandscapes-Deadline-10-2-Worker[sbom]",
    "OpenStudioLandscapes-Deadline-10-2-Worker[coverage]",
    "OpenStudioLandscapes-Deadline-10-2-Worker[readme]",
]

[tool.setuptools]
packages = [
    "OpenStudioLandscapes.Deadline_10_2_Worker"
]

[tool.dagster]
module_name = "OpenStudioLandscapes.Deadline_10_2_Worker.definitions"
code_location_name = "OpenStudioLandscapes-Deadline-10-2-Worker"
